/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/lufangzhou/Documents/work-space/personal/vuepressBlogBackup/node_modules/vuepress/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-1181f51d",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1181f51d").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6bdb318d",
    path: "/exampleMenu1/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bdb318d").then(next)
    },
  },
  {
    path: "/exampleMenu1/index.html",
    redirect: "/exampleMenu1/"
  },
  {
    name: "v-2d2fc0a6",
    path: "/exampleMenu1/exampleSubMenu1-a/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d2fc0a6").then(next)
    },
  },
  {
    path: "/exampleMenu1/exampleSubMenu1-a/index.html",
    redirect: "/exampleMenu1/exampleSubMenu1-a/"
  },
  {
    name: "v-35121228",
    path: "/exampleMenu1/exampleSubMenu1-a/file1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35121228").then(next)
    },
  },
  {
    name: "v-beb945ac",
    path: "/exampleMenu1/exampleSubMenu1-a/file2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-beb945ac").then(next)
    },
  },
  {
    name: "v-62ace2e6",
    path: "/exampleMenu1/exampleSubMenu1-b/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62ace2e6").then(next)
    },
  },
  {
    path: "/exampleMenu1/exampleSubMenu1-b/index.html",
    redirect: "/exampleMenu1/exampleSubMenu1-b/"
  },
  {
    name: "v-1b0136aa",
    path: "/exampleMenu1/exampleSubMenu1-b/file1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b0136aa").then(next)
    },
  },
  {
    name: "v-a6f5d7d0",
    path: "/hexo%E8%BF%81%E7%A7%BB/2018.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a6f5d7d0").then(next)
    },
  },
  {
    path: "/hexo迁移/2018.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/2018.html"
  },
  {
    path: "/hexo迁移/2018.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/2018.html"
  },
  {
    name: "v-11bc19da",
    path: "/hexo%E8%BF%81%E7%A7%BB/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11bc19da").then(next)
    },
  },
  {
    path: "/hexo迁移/",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/"
  },
  {
    path: "/hexo%E8%BF%81%E7%A7%BB/index.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/"
  },
  {
    path: "/hexo迁移/",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/"
  },
  {
    name: "v-52bf07b1",
    path: "/hexo%E8%BF%81%E7%A7%BB/Vue%E4%B8%AD%E6%95%B0%E7%BB%84%E8%B5%8B%E5%80%BC%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52bf07b1").then(next)
    },
  },
  {
    path: "/hexo迁移/Vue中数组赋值问题.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/Vue%E4%B8%AD%E6%95%B0%E7%BB%84%E8%B5%8B%E5%80%BC%E9%97%AE%E9%A2%98.html"
  },
  {
    path: "/hexo迁移/Vue中数组赋值问题.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/Vue%E4%B8%AD%E6%95%B0%E7%BB%84%E8%B5%8B%E5%80%BC%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-8ebd8a44",
    path: "/hexo%E8%BF%81%E7%A7%BB/hexo+github.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("photo", "v-8ebd8a44").then(next)
    },
  },
  {
    path: "/hexo迁移/hexo+github.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/hexo+github.html"
  },
  {
    path: "/hexo迁移/hexo+github.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/hexo+github.html"
  },
  {
    name: "v-71aca858",
    path: "/hexo%E8%BF%81%E7%A7%BB/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71aca858").then(next)
    },
  },
  {
    path: "/hexo迁移/markdown.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/markdown.html"
  },
  {
    path: "/hexo迁移/markdown.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/markdown.html"
  },
  {
    name: "v-54d9e9c2",
    path: "/hexo%E8%BF%81%E7%A7%BB/mpvue-entry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54d9e9c2").then(next)
    },
  },
  {
    path: "/hexo迁移/mpvue-entry.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/mpvue-entry.html"
  },
  {
    path: "/hexo迁移/mpvue-entry.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/mpvue-entry.html"
  },
  {
    name: "v-549711b8",
    path: "/hexo%E8%BF%81%E7%A7%BB/hexo-helper-live2d.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-549711b8").then(next)
    },
  },
  {
    path: "/hexo迁移/hexo-helper-live2d.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/hexo-helper-live2d.html"
  },
  {
    path: "/hexo迁移/hexo-helper-live2d.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/hexo-helper-live2d.html"
  },
  {
    name: "v-6a22b4f2",
    path: "/hexo%E8%BF%81%E7%A7%BB/vue%E4%B8%AD%E5%BC%95%E5%85%A5%E9%AB%98%E5%BE%B7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a22b4f2").then(next)
    },
  },
  {
    path: "/hexo迁移/vue中引入高德.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/vue%E4%B8%AD%E5%BC%95%E5%85%A5%E9%AB%98%E5%BE%B7.html"
  },
  {
    path: "/hexo迁移/vue中引入高德.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/vue%E4%B8%AD%E5%BC%95%E5%85%A5%E9%AB%98%E5%BE%B7.html"
  },
  {
    name: "v-1222c058",
    path: "/hexo%E8%BF%81%E7%A7%BB/npm%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1222c058").then(next)
    },
  },
  {
    path: "/hexo迁移/npm常用指令.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/npm%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4.html"
  },
  {
    path: "/hexo迁移/npm常用指令.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/npm%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4.html"
  },
  {
    name: "v-d79d234a",
    path: "/hexo%E8%BF%81%E7%A7%BB/vue%E7%BB%84%E4%BB%B6props%E4%BC%A0%E5%80%BC-%E5%AF%B9%E8%B1%A1%E8%8E%B7%E5%8F%96%E4%B8%8D%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d79d234a").then(next)
    },
  },
  {
    path: "/hexo迁移/vue组件props传值-对象获取不到的问题.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/vue%E7%BB%84%E4%BB%B6props%E4%BC%A0%E5%80%BC-%E5%AF%B9%E8%B1%A1%E8%8E%B7%E5%8F%96%E4%B8%8D%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98.html"
  },
  {
    path: "/hexo迁移/vue组件props传值-对象获取不到的问题.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/vue%E7%BB%84%E4%BB%B6props%E4%BC%A0%E5%80%BC-%E5%AF%B9%E8%B1%A1%E8%8E%B7%E5%8F%96%E4%B8%8D%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-08988cde",
    path: "/hexo%E8%BF%81%E7%A7%BB/vue%E7%9A%84computed-filters-watch.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08988cde").then(next)
    },
  },
  {
    path: "/hexo迁移/vue的computed-filters-watch.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/vue%E7%9A%84computed-filters-watch.html"
  },
  {
    path: "/hexo迁移/vue的computed-filters-watch.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/vue%E7%9A%84computed-filters-watch.html"
  },
  {
    name: "v-63b2ef91",
    path: "/hexo%E8%BF%81%E7%A7%BB/%E5%89%8D%E7%AB%AF%E5%AD%98%E5%82%A8%E6%8A%80%E6%9C%AF.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63b2ef91").then(next)
    },
  },
  {
    path: "/hexo迁移/前端存储技术.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E5%89%8D%E7%AB%AF%E5%AD%98%E5%82%A8%E6%8A%80%E6%9C%AF.html"
  },
  {
    path: "/hexo迁移/前端存储技术.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E5%89%8D%E7%AB%AF%E5%AD%98%E5%82%A8%E6%8A%80%E6%9C%AF.html"
  },
  {
    name: "v-32be9db2",
    path: "/hexo%E8%BF%81%E7%A7%BB/%E5%AF%BB%E6%A0%B9%E9%97%AE%E7%A5%96app%E7%9A%84%E5%B9%BB%E6%83%B3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32be9db2").then(next)
    },
  },
  {
    path: "/hexo迁移/寻根问祖app的幻想.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E5%AF%BB%E6%A0%B9%E9%97%AE%E7%A5%96app%E7%9A%84%E5%B9%BB%E6%83%B3.html"
  },
  {
    path: "/hexo迁移/寻根问祖app的幻想.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E5%AF%BB%E6%A0%B9%E9%97%AE%E7%A5%96app%E7%9A%84%E5%B9%BB%E6%83%B3.html"
  },
  {
    name: "v-7f20e659",
    path: "/hexo%E8%BF%81%E7%A7%BB/webpack%E5%AD%A6%E4%B9%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f20e659").then(next)
    },
  },
  {
    path: "/hexo迁移/webpack学习.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/webpack%E5%AD%A6%E4%B9%A0.html"
  },
  {
    path: "/hexo迁移/webpack学习.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/webpack%E5%AD%A6%E4%B9%A0.html"
  },
  {
    name: "v-2e2b0efa",
    path: "/hexo%E8%BF%81%E7%A7%BB/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%A1%86%E6%9E%B6mpvue%E4%B8%AD%E7%9A%84%E5%9D%91.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e2b0efa").then(next)
    },
  },
  {
    path: "/hexo迁移/小程序框架mpvue中的坑.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%A1%86%E6%9E%B6mpvue%E4%B8%AD%E7%9A%84%E5%9D%91.html"
  },
  {
    path: "/hexo迁移/小程序框架mpvue中的坑.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%A1%86%E6%9E%B6mpvue%E4%B8%AD%E7%9A%84%E5%9D%91.html"
  },
  {
    name: "v-31e4738d",
    path: "/hexo%E8%BF%81%E7%A7%BB/%E5%B1%8F%E5%B9%95%E6%BB%91%E5%8A%A8%E5%8A%A8%E7%94%BB%E6%96%B9%E6%A1%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31e4738d").then(next)
    },
  },
  {
    path: "/hexo迁移/屏幕滑动动画方案.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E5%B1%8F%E5%B9%95%E6%BB%91%E5%8A%A8%E5%8A%A8%E7%94%BB%E6%96%B9%E6%A1%88.html"
  },
  {
    path: "/hexo迁移/屏幕滑动动画方案.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E5%B1%8F%E5%B9%95%E6%BB%91%E5%8A%A8%E5%8A%A8%E7%94%BB%E6%96%B9%E6%A1%88.html"
  },
  {
    name: "v-368015ed",
    path: "/hexo%E8%BF%81%E7%A7%BB/%E6%96%AD%E7%BD%91%E5%A4%84%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-368015ed").then(next)
    },
  },
  {
    path: "/hexo迁移/断网处理.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E6%96%AD%E7%BD%91%E5%A4%84%E7%90%86.html"
  },
  {
    path: "/hexo迁移/断网处理.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E6%96%AD%E7%BD%91%E5%A4%84%E7%90%86.html"
  },
  {
    name: "v-05d85f8d",
    path: "/hexo%E8%BF%81%E7%A7%BB/%E6%96%B9%E6%B3%95%E5%90%8D%E4%B8%8E%E5%8F%98%E9%87%8F%E5%90%8D%E9%87%8D%E5%90%8D%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05d85f8d").then(next)
    },
  },
  {
    path: "/hexo迁移/方法名与变量名重名问题.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E6%96%B9%E6%B3%95%E5%90%8D%E4%B8%8E%E5%8F%98%E9%87%8F%E5%90%8D%E9%87%8D%E5%90%8D%E9%97%AE%E9%A2%98.html"
  },
  {
    path: "/hexo迁移/方法名与变量名重名问题.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E6%96%B9%E6%B3%95%E5%90%8D%E4%B8%8E%E5%8F%98%E9%87%8F%E5%90%8D%E9%87%8D%E5%90%8D%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-65cf4b51",
    path: "/hexo%E8%BF%81%E7%A7%BB/%E6%B5%85%E8%B0%88v-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65cf4b51").then(next)
    },
  },
  {
    path: "/hexo迁移/浅谈v-slot.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E6%B5%85%E8%B0%88v-slot.html"
  },
  {
    path: "/hexo迁移/浅谈v-slot.html",
    redirect: "/hexo%E8%BF%81%E7%A7%BB/%E6%B5%85%E8%B0%88v-slot.html"
  },
  {
    name: "v-379e185a",
    path: "/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8/howToUse.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-379e185a").then(next)
    },
  },
  {
    path: "/如何使用/howToUse.html",
    redirect: "/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8/howToUse.html"
  },
  {
    path: "/如何使用/howToUse.html",
    redirect: "/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8/howToUse.html"
  },
  {
    name: "v-052a06a3",
    path: "/%E6%A1%86%E6%9E%B6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-052a06a3").then(next)
    },
  },
  {
    path: "/框架/",
    redirect: "/%E6%A1%86%E6%9E%B6/"
  },
  {
    path: "/%E6%A1%86%E6%9E%B6/index.html",
    redirect: "/%E6%A1%86%E6%9E%B6/"
  },
  {
    path: "/框架/",
    redirect: "/%E6%A1%86%E6%9E%B6/"
  },
  {
    name: "v-491b68e8",
    path: "/%E6%A1%86%E6%9E%B6/vue-dynamic-router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-491b68e8").then(next)
    },
  },
  {
    path: "/框架/vue-dynamic-router.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-dynamic-router.html"
  },
  {
    path: "/框架/vue-dynamic-router.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-dynamic-router.html"
  },
  {
    name: "v-e269e068",
    path: "/%E6%A1%86%E6%9E%B6/vue-props.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e269e068").then(next)
    },
  },
  {
    path: "/框架/vue-props.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-props.html"
  },
  {
    path: "/框架/vue-props.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-props.html"
  },
  {
    name: "v-0ff677f2",
    path: "/%E6%A1%86%E6%9E%B6/vue-seo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ff677f2").then(next)
    },
  },
  {
    path: "/框架/vue-seo.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-seo.html"
  },
  {
    path: "/框架/vue-seo.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-seo.html"
  },
  {
    name: "v-6c22ecb0",
    path: "/%E6%A1%86%E6%9E%B6/vue-router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c22ecb0").then(next)
    },
  },
  {
    path: "/框架/vue-router.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-router.html"
  },
  {
    path: "/框架/vue-router.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-router.html"
  },
  {
    name: "v-7027d348",
    path: "/%E6%A1%86%E6%9E%B6/vue-vite.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7027d348").then(next)
    },
  },
  {
    path: "/框架/vue-vite.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-vite.html"
  },
  {
    path: "/框架/vue-vite.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-vite.html"
  },
  {
    name: "v-39beb45d",
    path: "/%E6%A1%86%E6%9E%B6/vue-%E5%88%9D%E6%8E%A2vue3%E5%93%8D%E5%BA%94%E6%80%A7%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39beb45d").then(next)
    },
  },
  {
    path: "/框架/vue-初探vue3响应性基础.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-%E5%88%9D%E6%8E%A2vue3%E5%93%8D%E5%BA%94%E6%80%A7%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/框架/vue-初探vue3响应性基础.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-%E5%88%9D%E6%8E%A2vue3%E5%93%8D%E5%BA%94%E6%80%A7%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-5e595f02",
    path: "/%E6%A1%86%E6%9E%B6/vue-%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e595f02").then(next)
    },
  },
  {
    path: "/框架/vue-生命周期.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html"
  },
  {
    path: "/框架/vue-生命周期.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html"
  },
  {
    name: "v-b5cf85b0",
    path: "/%E6%A1%86%E6%9E%B6/vue-%E8%87%AA%E5%8A%A8%E5%8C%96%E6%A8%A1%E5%9D%97.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b5cf85b0").then(next)
    },
  },
  {
    path: "/框架/vue-自动化模块.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-%E8%87%AA%E5%8A%A8%E5%8C%96%E6%A8%A1%E5%9D%97.html"
  },
  {
    path: "/框架/vue-自动化模块.html",
    redirect: "/%E6%A1%86%E6%9E%B6/vue-%E8%87%AA%E5%8A%A8%E5%8C%96%E6%A8%A1%E5%9D%97.html"
  },
  {
    name: "v-318df56c",
    path: "/%E8%AF%AD%E8%A8%80/Generator.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-318df56c").then(next)
    },
  },
  {
    path: "/语言/Generator.html",
    redirect: "/%E8%AF%AD%E8%A8%80/Generator.html"
  },
  {
    path: "/语言/Generator.html",
    redirect: "/%E8%AF%AD%E8%A8%80/Generator.html"
  },
  {
    name: "v-4b8d5286",
    path: "/%E8%AF%AD%E8%A8%80/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b8d5286").then(next)
    },
  },
  {
    path: "/语言/",
    redirect: "/%E8%AF%AD%E8%A8%80/"
  },
  {
    path: "/%E8%AF%AD%E8%A8%80/index.html",
    redirect: "/%E8%AF%AD%E8%A8%80/"
  },
  {
    path: "/语言/",
    redirect: "/%E8%AF%AD%E8%A8%80/"
  },
  {
    name: "v-75d48a2e",
    path: "/%E8%AF%AD%E8%A8%80/String.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75d48a2e").then(next)
    },
  },
  {
    path: "/语言/String.html",
    redirect: "/%E8%AF%AD%E8%A8%80/String.html"
  },
  {
    path: "/语言/String.html",
    redirect: "/%E8%AF%AD%E8%A8%80/String.html"
  },
  {
    name: "v-a2dcaef6",
    path: "/%E8%AF%AD%E8%A8%80/array%E7%94%A8%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a2dcaef6").then(next)
    },
  },
  {
    path: "/语言/array用法.html",
    redirect: "/%E8%AF%AD%E8%A8%80/array%E7%94%A8%E6%B3%95.html"
  },
  {
    path: "/语言/array用法.html",
    redirect: "/%E8%AF%AD%E8%A8%80/array%E7%94%A8%E6%B3%95.html"
  },
  {
    name: "v-5734b83e",
    path: "/%E8%AF%AD%E8%A8%80/echarts%E6%B8%B2%E6%9F%93%E5%AE%8C%E6%88%90%E4%BA%8B%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5734b83e").then(next)
    },
  },
  {
    path: "/语言/echarts渲染完成事件.html",
    redirect: "/%E8%AF%AD%E8%A8%80/echarts%E6%B8%B2%E6%9F%93%E5%AE%8C%E6%88%90%E4%BA%8B%E4%BB%B6.html"
  },
  {
    path: "/语言/echarts渲染完成事件.html",
    redirect: "/%E8%AF%AD%E8%A8%80/echarts%E6%B8%B2%E6%9F%93%E5%AE%8C%E6%88%90%E4%BA%8B%E4%BB%B6.html"
  },
  {
    name: "v-327cbd60",
    path: "/%E8%AF%AD%E8%A8%80/interview.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-327cbd60").then(next)
    },
  },
  {
    path: "/语言/interview.html",
    redirect: "/%E8%AF%AD%E8%A8%80/interview.html"
  },
  {
    path: "/语言/interview.html",
    redirect: "/%E8%AF%AD%E8%A8%80/interview.html"
  },
  {
    name: "v-4f2b2c50",
    path: "/%E8%AF%AD%E8%A8%80/css-%E7%AC%94%E8%AE%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f2b2c50").then(next)
    },
  },
  {
    path: "/语言/css-笔记.html",
    redirect: "/%E8%AF%AD%E8%A8%80/css-%E7%AC%94%E8%AE%B0.html"
  },
  {
    path: "/语言/css-笔记.html",
    redirect: "/%E8%AF%AD%E8%A8%80/css-%E7%AC%94%E8%AE%B0.html"
  },
  {
    name: "v-014afd87",
    path: "/%E8%AF%AD%E8%A8%80/let%E4%B8%8Evar.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-014afd87").then(next)
    },
  },
  {
    path: "/语言/let与var.html",
    redirect: "/%E8%AF%AD%E8%A8%80/let%E4%B8%8Evar.html"
  },
  {
    path: "/语言/let与var.html",
    redirect: "/%E8%AF%AD%E8%A8%80/let%E4%B8%8Evar.html"
  },
  {
    name: "v-3b6fbcb6",
    path: "/%E8%AF%AD%E8%A8%80/proxy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b6fbcb6").then(next)
    },
  },
  {
    path: "/语言/proxy.html",
    redirect: "/%E8%AF%AD%E8%A8%80/proxy.html"
  },
  {
    path: "/语言/proxy.html",
    redirect: "/%E8%AF%AD%E8%A8%80/proxy.html"
  },
  {
    name: "v-72a6a583",
    path: "/%E8%AF%AD%E8%A8%80/tsx+ts+vue3%E8%AF%AD%E6%B3%95%E7%AC%94%E8%AE%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72a6a583").then(next)
    },
  },
  {
    path: "/语言/tsx+ts+vue3语法笔记.html",
    redirect: "/%E8%AF%AD%E8%A8%80/tsx+ts+vue3%E8%AF%AD%E6%B3%95%E7%AC%94%E8%AE%B0.html"
  },
  {
    path: "/语言/tsx+ts+vue3语法笔记.html",
    redirect: "/%E8%AF%AD%E8%A8%80/tsx+ts+vue3%E8%AF%AD%E6%B3%95%E7%AC%94%E8%AE%B0.html"
  },
  {
    name: "v-03b6ac0e",
    path: "/%E8%AF%AD%E8%A8%80/util.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03b6ac0e").then(next)
    },
  },
  {
    path: "/语言/util.html",
    redirect: "/%E8%AF%AD%E8%A8%80/util.html"
  },
  {
    path: "/语言/util.html",
    redirect: "/%E8%AF%AD%E8%A8%80/util.html"
  },
  {
    name: "v-2d399ebb",
    path: "/%E8%AF%AD%E8%A8%80/setInterval%E5%8A%A8%E6%80%81%E8%AE%BE%E7%BD%AE%E6%97%B6%E9%97%B4%20.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d399ebb").then(next)
    },
  },
  {
    path: "/语言/setInterval动态设置时间 .html",
    redirect: "/%E8%AF%AD%E8%A8%80/setInterval%E5%8A%A8%E6%80%81%E8%AE%BE%E7%BD%AE%E6%97%B6%E9%97%B4%20.html"
  },
  {
    path: "/语言/setInterval动态设置时间 .html",
    redirect: "/%E8%AF%AD%E8%A8%80/setInterval%E5%8A%A8%E6%80%81%E8%AE%BE%E7%BD%AE%E6%97%B6%E9%97%B4%20.html"
  },
  {
    name: "v-986d8176",
    path: "/%E8%AF%AD%E8%A8%80/%E5%9C%A8TSX%E4%B8%AD%E7%8E%A9%E8%BD%ACvue3%E5%8A%A8%E6%80%81%E7%BB%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-986d8176").then(next)
    },
  },
  {
    path: "/语言/在TSX中玩转vue3动态组件.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E5%9C%A8TSX%E4%B8%AD%E7%8E%A9%E8%BD%ACvue3%E5%8A%A8%E6%80%81%E7%BB%84%E4%BB%B6.html"
  },
  {
    path: "/语言/在TSX中玩转vue3动态组件.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E5%9C%A8TSX%E4%B8%AD%E7%8E%A9%E8%BD%ACvue3%E5%8A%A8%E6%80%81%E7%BB%84%E4%BB%B6.html"
  },
  {
    name: "v-3f17de72",
    path: "/%E8%AF%AD%E8%A8%80/vue3+tsx%E5%9B%9E%E8%BD%A6%E4%BA%8B%E4%BB%B6%E7%AE%80%E5%8D%95%E5%86%99%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f17de72").then(next)
    },
  },
  {
    path: "/语言/vue3+tsx回车事件简单写法.html",
    redirect: "/%E8%AF%AD%E8%A8%80/vue3+tsx%E5%9B%9E%E8%BD%A6%E4%BA%8B%E4%BB%B6%E7%AE%80%E5%8D%95%E5%86%99%E6%B3%95.html"
  },
  {
    path: "/语言/vue3+tsx回车事件简单写法.html",
    redirect: "/%E8%AF%AD%E8%A8%80/vue3+tsx%E5%9B%9E%E8%BD%A6%E4%BA%8B%E4%BB%B6%E7%AE%80%E5%8D%95%E5%86%99%E6%B3%95.html"
  },
  {
    name: "v-0d3a2328",
    path: "/%E8%AF%AD%E8%A8%80/%E5%88%A4%E6%96%AD%E7%B1%BB%E5%9E%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d3a2328").then(next)
    },
  },
  {
    path: "/语言/判断类型.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E5%88%A4%E6%96%AD%E7%B1%BB%E5%9E%8B.html"
  },
  {
    path: "/语言/判断类型.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E5%88%A4%E6%96%AD%E7%B1%BB%E5%9E%8B.html"
  },
  {
    name: "v-513f8d42",
    path: "/%E8%AF%AD%E8%A8%80/%E6%89%8B%E6%91%B8%E6%89%8B%E6%95%99%E4%BD%A0%E5%B0%81%E8%A3%85echarts%E8%87%AA%E9%80%82%E5%BA%94%E5%A4%A7%E5%B0%8F%E7%BB%84%E4%BB%B6%EF%BC%88%E8%8A%82%E6%B5%81%E7%89%88%EF%BC%89%20.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-513f8d42").then(next)
    },
  },
  {
    path: "/语言/手摸手教你封装echarts自适应大小组件（节流版） .html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E6%89%8B%E6%91%B8%E6%89%8B%E6%95%99%E4%BD%A0%E5%B0%81%E8%A3%85echarts%E8%87%AA%E9%80%82%E5%BA%94%E5%A4%A7%E5%B0%8F%E7%BB%84%E4%BB%B6%EF%BC%88%E8%8A%82%E6%B5%81%E7%89%88%EF%BC%89%20.html"
  },
  {
    path: "/语言/手摸手教你封装echarts自适应大小组件（节流版） .html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E6%89%8B%E6%91%B8%E6%89%8B%E6%95%99%E4%BD%A0%E5%B0%81%E8%A3%85echarts%E8%87%AA%E9%80%82%E5%BA%94%E5%A4%A7%E5%B0%8F%E7%BB%84%E4%BB%B6%EF%BC%88%E8%8A%82%E6%B5%81%E7%89%88%EF%BC%89%20.html"
  },
  {
    name: "v-3b0e0804",
    path: "/%E8%AF%AD%E8%A8%80/%E7%9C%9F%E6%AD%A3%E7%90%86%E8%A7%A3%E9%98%B2%E6%8A%96%E8%8A%82%E6%B5%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b0e0804").then(next)
    },
  },
  {
    path: "/语言/真正理解防抖节流.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E7%9C%9F%E6%AD%A3%E7%90%86%E8%A7%A3%E9%98%B2%E6%8A%96%E8%8A%82%E6%B5%81.html"
  },
  {
    path: "/语言/真正理解防抖节流.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E7%9C%9F%E6%AD%A3%E7%90%86%E8%A7%A3%E9%98%B2%E6%8A%96%E8%8A%82%E6%B5%81.html"
  },
  {
    name: "v-26574814",
    path: "/%E8%AF%AD%E8%A8%80/%E5%BC%82%E6%AD%A5%E7%BC%96%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26574814").then(next)
    },
  },
  {
    path: "/语言/异步编程.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E5%BC%82%E6%AD%A5%E7%BC%96%E7%A8%8B.html"
  },
  {
    path: "/语言/异步编程.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E5%BC%82%E6%AD%A5%E7%BC%96%E7%A8%8B.html"
  },
  {
    name: "v-c37b03ce",
    path: "/%E8%AF%AD%E8%A8%80/%E8%AF%95%E7%94%A8%E4%BA%AC%E4%B8%9Cmicro-app%E5%BE%AE%E5%89%8D%E7%AB%AF%E6%A1%86%E6%9E%B6,%E5%85%BC%E5%AE%B9vite.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c37b03ce").then(next)
    },
  },
  {
    path: "/语言/试用京东micro-app微前端框架,兼容vite.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E8%AF%95%E7%94%A8%E4%BA%AC%E4%B8%9Cmicro-app%E5%BE%AE%E5%89%8D%E7%AB%AF%E6%A1%86%E6%9E%B6,%E5%85%BC%E5%AE%B9vite.html"
  },
  {
    path: "/语言/试用京东micro-app微前端框架,兼容vite.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E8%AF%95%E7%94%A8%E4%BA%AC%E4%B8%9Cmicro-app%E5%BE%AE%E5%89%8D%E7%AB%AF%E6%A1%86%E6%9E%B6,%E5%85%BC%E5%AE%B9vite.html"
  },
  {
    name: "v-4bbfad74",
    path: "/%E8%AF%AD%E8%A8%80/%E6%8B%B7%E8%B4%9D%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bbfad74").then(next)
    },
  },
  {
    path: "/语言/拷贝问题.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E6%8B%B7%E8%B4%9D%E9%97%AE%E9%A2%98.html"
  },
  {
    path: "/语言/拷贝问题.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E6%8B%B7%E8%B4%9D%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-db97e196",
    path: "/%E8%AF%AD%E8%A8%80/%E9%A1%B9%E7%9B%AE%E9%80%9A%E7%94%A8scss.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db97e196").then(next)
    },
  },
  {
    path: "/语言/项目通用scss.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E9%A1%B9%E7%9B%AE%E9%80%9A%E7%94%A8scss.html"
  },
  {
    path: "/语言/项目通用scss.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E9%A1%B9%E7%9B%AE%E9%80%9A%E7%94%A8scss.html"
  },
  {
    name: "v-14104ec7",
    path: "/%E9%98%85%E8%AF%BB/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14104ec7").then(next)
    },
  },
  {
    path: "/阅读/",
    redirect: "/%E9%98%85%E8%AF%BB/"
  },
  {
    path: "/%E9%98%85%E8%AF%BB/index.html",
    redirect: "/%E9%98%85%E8%AF%BB/"
  },
  {
    path: "/阅读/",
    redirect: "/%E9%98%85%E8%AF%BB/"
  },
  {
    name: "v-86cd0aa8",
    path: "/%E9%98%85%E8%AF%BB/%E7%BA%A2%E5%AE%9D%E4%B9%A6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-86cd0aa8").then(next)
    },
  },
  {
    path: "/阅读/红宝书.html",
    redirect: "/%E9%98%85%E8%AF%BB/%E7%BA%A2%E5%AE%9D%E4%B9%A6.html"
  },
  {
    path: "/阅读/红宝书.html",
    redirect: "/%E9%98%85%E8%AF%BB/%E7%BA%A2%E5%AE%9D%E4%B9%A6.html"
  },
  {
    name: "v-a0db9738",
    path: "/%E8%AF%AD%E8%A8%80/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E5%9B%BE%E7%89%87%E9%A2%84%E5%8A%A0%E8%BD%BD%20.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a0db9738").then(next)
    },
  },
  {
    path: "/语言/如何实现图片预加载 .html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E5%9B%BE%E7%89%87%E9%A2%84%E5%8A%A0%E8%BD%BD%20.html"
  },
  {
    path: "/语言/如何实现图片预加载 .html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E5%9B%BE%E7%89%87%E9%A2%84%E5%8A%A0%E8%BD%BD%20.html"
  },
  {
    name: "v-60f647eb",
    path: "/%E8%AF%AD%E8%A8%80/%E7%90%86%E8%A7%A3js%E4%B8%AD%E6%B7%B1%E5%BA%A6%E4%BC%98%E5%85%88%E5%92%8C%E5%B9%BF%E5%BA%A6%E4%BC%98%E5%85%88%E6%90%9C%E7%B4%A2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60f647eb").then(next)
    },
  },
  {
    path: "/语言/理解js中深度优先和广度优先搜索.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E7%90%86%E8%A7%A3js%E4%B8%AD%E6%B7%B1%E5%BA%A6%E4%BC%98%E5%85%88%E5%92%8C%E5%B9%BF%E5%BA%A6%E4%BC%98%E5%85%88%E6%90%9C%E7%B4%A2.html"
  },
  {
    path: "/语言/理解js中深度优先和广度优先搜索.html",
    redirect: "/%E8%AF%AD%E8%A8%80/%E7%90%86%E8%A7%A3js%E4%B8%AD%E6%B7%B1%E5%BA%A6%E4%BC%98%E5%85%88%E5%92%8C%E5%B9%BF%E5%BA%A6%E4%BC%98%E5%85%88%E6%90%9C%E7%B4%A2.html"
  },
  {
    name: "v-20358fac",
    path: "/%E9%9A%8F%E7%AC%94/annual-summary-2022.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20358fac").then(next)
    },
  },
  {
    path: "/随笔/annual-summary-2022.html",
    redirect: "/%E9%9A%8F%E7%AC%94/annual-summary-2022.html"
  },
  {
    path: "/随笔/annual-summary-2022.html",
    redirect: "/%E9%9A%8F%E7%AC%94/annual-summary-2022.html"
  },
  {
    name: "v-7b8811ec",
    path: "/%E9%9A%8F%E7%AC%94/charts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b8811ec").then(next)
    },
  },
  {
    path: "/随笔/charts.html",
    redirect: "/%E9%9A%8F%E7%AC%94/charts.html"
  },
  {
    path: "/随笔/charts.html",
    redirect: "/%E9%9A%8F%E7%AC%94/charts.html"
  },
  {
    name: "v-7c4e4e8d",
    path: "/%E9%9A%8F%E7%AC%94/%E5%9B%9E%E5%BF%86%E5%BD%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c4e4e8d").then(next)
    },
  },
  {
    path: "/随笔/回忆录.html",
    redirect: "/%E9%9A%8F%E7%AC%94/%E5%9B%9E%E5%BF%86%E5%BD%95.html"
  },
  {
    path: "/随笔/回忆录.html",
    redirect: "/%E9%9A%8F%E7%AC%94/%E5%9B%9E%E5%BF%86%E5%BD%95.html"
  },
  {
    name: "v-dc7de658",
    path: "/%E9%9A%8F%E7%AC%94/%E8%AE%B0%E5%BD%95%E6%97%85%E6%B8%B8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dc7de658").then(next)
    },
  },
  {
    path: "/随笔/记录旅游.html",
    redirect: "/%E9%9A%8F%E7%AC%94/%E8%AE%B0%E5%BD%95%E6%97%85%E6%B8%B8.html"
  },
  {
    path: "/随笔/记录旅游.html",
    redirect: "/%E9%9A%8F%E7%AC%94/%E8%AE%B0%E5%BD%95%E6%97%85%E6%B8%B8.html"
  },
  {
    name: "v-b25a9d7c",
    path: "/%E9%9A%8F%E7%AC%94/%E8%AE%B0%E5%BD%95%E5%BC%80%E5%8F%91%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b25a9d7c").then(next)
    },
  },
  {
    path: "/随笔/记录开发问题.html",
    redirect: "/%E9%9A%8F%E7%AC%94/%E8%AE%B0%E5%BD%95%E5%BC%80%E5%8F%91%E9%97%AE%E9%A2%98.html"
  },
  {
    path: "/随笔/记录开发问题.html",
    redirect: "/%E9%9A%8F%E7%AC%94/%E8%AE%B0%E5%BD%95%E5%BC%80%E5%8F%91%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-328cc28c",
    path: "/%E9%9A%8F%E7%AC%94/%E8%AE%B0%E5%BD%95%E6%A2%A6%E5%A2%83.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-328cc28c").then(next)
    },
  },
  {
    path: "/随笔/记录梦境.html",
    redirect: "/%E9%9A%8F%E7%AC%94/%E8%AE%B0%E5%BD%95%E6%A2%A6%E5%A2%83.html"
  },
  {
    path: "/随笔/记录梦境.html",
    redirect: "/%E9%9A%8F%E7%AC%94/%E8%AE%B0%E5%BD%95%E6%A2%A6%E5%A2%83.html"
  },
  {
    name: "v-a625822a",
    path: "/%E9%9A%8F%E7%AC%94/%E8%AE%B0%E5%BD%95%E6%B8%B8%E6%88%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a625822a").then(next)
    },
  },
  {
    path: "/随笔/记录游戏.html",
    redirect: "/%E9%9A%8F%E7%AC%94/%E8%AE%B0%E5%BD%95%E6%B8%B8%E6%88%8F.html"
  },
  {
    path: "/随笔/记录游戏.html",
    redirect: "/%E9%9A%8F%E7%AC%94/%E8%AE%B0%E5%BD%95%E6%B8%B8%E6%88%8F.html"
  },
  {
    name: "v-7f7258e1",
    path: "/%E9%9A%8F%E7%AC%94/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f7258e1").then(next)
    },
  },
  {
    path: "/随笔/",
    redirect: "/%E9%9A%8F%E7%AC%94/"
  },
  {
    path: "/%E9%9A%8F%E7%AC%94/index.html",
    redirect: "/%E9%9A%8F%E7%AC%94/"
  },
  {
    path: "/随笔/",
    redirect: "/%E9%9A%8F%E7%AC%94/"
  },
  {
    name: "v-3693d5a4",
    path: "/%E9%9A%8F%E7%AC%94/annual-summary-2021.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3693d5a4").then(next)
    },
  },
  {
    path: "/随笔/annual-summary-2021.html",
    redirect: "/%E9%9A%8F%E7%AC%94/annual-summary-2021.html"
  },
  {
    path: "/随笔/annual-summary-2021.html",
    redirect: "/%E9%9A%8F%E7%AC%94/annual-summary-2021.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-322a45da",
    path: "/tag/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322a45da").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/index.html",
    redirect: "/tag/vue/"
  },
  {
    name: "v-14b6f4de",
    path: "/tag/hexo/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-14b6f4de").then(next)
    },
    meta: {"pid":"tags","id":"hexo"}
  },
  {
    path: "/tag/hexo/index.html",
    redirect: "/tag/hexo/"
  },
  {
    name: "v-1f67da7c",
    path: "/tag/github/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1f67da7c").then(next)
    },
    meta: {"pid":"tags","id":"github"}
  },
  {
    path: "/tag/github/index.html",
    redirect: "/tag/github/"
  },
  {
    name: "v-3ae5b494",
    path: "/tag/markdown/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3ae5b494").then(next)
    },
    meta: {"pid":"tags","id":"markdown"}
  },
  {
    path: "/tag/markdown/index.html",
    redirect: "/tag/markdown/"
  },
  {
    name: "v-097a1baa",
    path: "/tag/小程序/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-097a1baa").then(next)
    },
    meta: {"pid":"tags","id":"小程序"}
  },
  {
    path: "/tag/小程序/index.html",
    redirect: "/tag/小程序/"
  },
  {
    name: "v-3231af64",
    path: "/tag/npm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3231af64").then(next)
    },
    meta: {"pid":"tags","id":"npm"}
  },
  {
    path: "/tag/npm/index.html",
    redirect: "/tag/npm/"
  },
  {
    name: "v-26aaf461",
    path: "/tag/cookie/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-26aaf461").then(next)
    },
    meta: {"pid":"tags","id":"cookie"}
  },
  {
    path: "/tag/cookie/index.html",
    redirect: "/tag/cookie/"
  },
  {
    name: "v-35a49dbe",
    path: "/tag/storage/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-35a49dbe").then(next)
    },
    meta: {"pid":"tags","id":"storage"}
  },
  {
    path: "/tag/storage/index.html",
    redirect: "/tag/storage/"
  },
  {
    name: "v-5b405b0a",
    path: "/tag/indexedDB/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5b405b0a").then(next)
    },
    meta: {"pid":"tags","id":"indexedDB"}
  },
  {
    path: "/tag/indexedDB/index.html",
    redirect: "/tag/indexedDB/"
  },
  {
    name: "v-3446f207",
    path: "/tag/原型/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3446f207").then(next)
    },
    meta: {"pid":"tags","id":"原型"}
  },
  {
    path: "/tag/原型/index.html",
    redirect: "/tag/原型/"
  },
  {
    name: "v-b53ec9e8",
    path: "/tag/webpack/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-b53ec9e8").then(next)
    },
    meta: {"pid":"tags","id":"webpack"}
  },
  {
    path: "/tag/webpack/index.html",
    redirect: "/tag/webpack/"
  },
  {
    name: "v-6fe2c294",
    path: "/tag/mpvue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-6fe2c294").then(next)
    },
    meta: {"pid":"tags","id":"mpvue"}
  },
  {
    path: "/tag/mpvue/index.html",
    redirect: "/tag/mpvue/"
  },
  {
    name: "v-13304f98",
    path: "/tag/vant/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-13304f98").then(next)
    },
    meta: {"pid":"tags","id":"vant"}
  },
  {
    path: "/tag/vant/index.html",
    redirect: "/tag/vant/"
  },
  {
    name: "v-323b9794",
    path: "/tag/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-323b9794").then(next)
    },
    meta: {"pid":"tags","id":"css"}
  },
  {
    path: "/tag/css/index.html",
    redirect: "/tag/css/"
  },
  {
    name: "v-980194ba",
    path: "/tag/axios/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-980194ba").then(next)
    },
    meta: {"pid":"tags","id":"axios"}
  },
  {
    path: "/tag/axios/index.html",
    redirect: "/tag/axios/"
  },
  {
    name: "v-07a3e910",
    path: "/tag/javascript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-07a3e910").then(next)
    },
    meta: {"pid":"tags","id":"javascript"}
  },
  {
    path: "/tag/javascript/index.html",
    redirect: "/tag/javascript/"
  },
  {
    name: "v-601bec8c",
    path: "/tag/react/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-601bec8c").then(next)
    },
    meta: {"pid":"tags","id":"react"}
  },
  {
    path: "/tag/react/index.html",
    redirect: "/tag/react/"
  },
  {
    name: "v-657392aa",
    path: "/tag/proxy/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-657392aa").then(next)
    },
    meta: {"pid":"tags","id":"proxy"}
  },
  {
    path: "/tag/proxy/index.html",
    redirect: "/tag/proxy/"
  },
  {
    name: "v-1966d78c",
    path: "/tag/红宝书/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1966d78c").then(next)
    },
    meta: {"pid":"tags","id":"红宝书"}
  },
  {
    path: "/tag/红宝书/index.html",
    redirect: "/tag/红宝书/"
  },
  {
    name: "v-bc0ad0be",
    path: "/tag/回忆录/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-bc0ad0be").then(next)
    },
    meta: {"pid":"tags","id":"回忆录"}
  },
  {
    path: "/tag/回忆录/index.html",
    redirect: "/tag/回忆录/"
  },
  {
    name: "v-19f71890",
    path: "/tag/charts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-19f71890").then(next)
    },
    meta: {"pid":"tags","id":"charts"}
  },
  {
    path: "/tag/charts/index.html",
    redirect: "/tag/charts/"
  },
  {
    name: "v-104f6ca4",
    path: "/tag/旅游/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-104f6ca4").then(next)
    },
    meta: {"pid":"tags","id":"旅游"}
  },
  {
    path: "/tag/旅游/index.html",
    redirect: "/tag/旅游/"
  },
  {
    name: "v-09498bac",
    path: "/tag/开发问题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-09498bac").then(next)
    },
    meta: {"pid":"tags","id":"开发问题"}
  },
  {
    path: "/tag/开发问题/index.html",
    redirect: "/tag/开发问题/"
  },
  {
    name: "v-11c0ed14",
    path: "/tag/游戏, 电影, 书籍/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-11c0ed14").then(next)
    },
    meta: {"pid":"tags","id":"游戏, 电影, 书籍"}
  },
  {
    path: "/tag/游戏, 电影, 书籍/index.html",
    redirect: "/tag/游戏, 电影, 书籍/"
  },
  {
    name: "v-5d015807",
    path: "/tag/事件时间线/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5d015807").then(next)
    },
    meta: {"pid":"tags","id":"事件时间线"}
  },
  {
    path: "/tag/事件时间线/index.html",
    redirect: "/tag/事件时间线/"
  },
  {
    name: "v-2bf76980",
    path: "/categories/随笔/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-2bf76980").then(next)
    },
    meta: {"pid":"categories","id":"随笔"}
  },
  {
    path: "/categories/随笔/index.html",
    redirect: "/categories/随笔/"
  },
  {
    name: "v-3562c712",
    path: "/categories/框架/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-3562c712").then(next)
    },
    meta: {"pid":"categories","id":"框架"}
  },
  {
    path: "/categories/框架/index.html",
    redirect: "/categories/框架/"
  },
  {
    name: "v-33c9dede",
    path: "/categories/其它/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-33c9dede").then(next)
    },
    meta: {"pid":"categories","id":"其它"}
  },
  {
    path: "/categories/其它/index.html",
    redirect: "/categories/其它/"
  },
  {
    name: "v-5446404e",
    path: "/categories/语言/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-5446404e").then(next)
    },
    meta: {"pid":"categories","id":"语言"}
  },
  {
    path: "/categories/语言/index.html",
    redirect: "/categories/语言/"
  },
  {
    name: "v-aa513fce",
    path: "/categories/打包/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-aa513fce").then(next)
    },
    meta: {"pid":"categories","id":"打包"}
  },
  {
    path: "/categories/打包/index.html",
    redirect: "/categories/打包/"
  },
  {
    name: "v-c53aecda",
    path: "/categories/echarts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-c53aecda").then(next)
    },
    meta: {"pid":"categories","id":"echarts"}
  },
  {
    path: "/categories/echarts/index.html",
    redirect: "/categories/echarts/"
  },
  {
    name: "v-417c2884",
    path: "/categories/javascript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-417c2884").then(next)
    },
    meta: {"pid":"categories","id":"javascript"}
  },
  {
    path: "/categories/javascript/index.html",
    redirect: "/categories/javascript/"
  },
  {
    name: "v-7e13ecb5",
    path: "/categories/阅读/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7e13ecb5").then(next)
    },
    meta: {"pid":"categories","id":"阅读"}
  },
  {
    path: "/categories/阅读/index.html",
    redirect: "/categories/阅读/"
  },
  {
    name: "v-4762ed4a",
    path: "/tag/vue/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4762ed4a").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/page/2/index.html",
    redirect: "/tag/vue/page/2/"
  },
  {
    name: "v-7ab29976",
    path: "/tag/javascript/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ab29976").then(next)
    },
    meta: {"pid":"tags","id":"javascript"}
  },
  {
    path: "/tag/javascript/page/2/index.html",
    redirect: "/tag/javascript/page/2/"
  },
  {
    name: "v-7ab29938",
    path: "/tag/javascript/page/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ab29938").then(next)
    },
    meta: {"pid":"tags","id":"javascript"}
  },
  {
    path: "/tag/javascript/page/3/index.html",
    redirect: "/tag/javascript/page/3/"
  },
  {
    name: "v-780fd566",
    path: "/categories/框架/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-780fd566").then(next)
    },
    meta: {"pid":"categories","id":"框架"}
  },
  {
    path: "/categories/框架/page/2/index.html",
    redirect: "/categories/框架/page/2/"
  },
  {
    name: "v-32e781af",
    path: "/categories/语言/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32e781af").then(next)
    },
    meta: {"pid":"categories","id":"语言"}
  },
  {
    path: "/categories/语言/page/2/index.html",
    redirect: "/categories/语言/page/2/"
  },
  {
    name: "v-32e781ce",
    path: "/categories/语言/page/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32e781ce").then(next)
    },
    meta: {"pid":"categories","id":"语言"}
  },
  {
    path: "/categories/语言/page/3/index.html",
    redirect: "/categories/语言/page/3/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]