/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-52bf07b1",
        "v-54d9e9c2",
        "v-6a22b4f2",
        "v-d79d234a",
        "v-08988cde",
        "v-2e2b0efa",
        "v-368015ed",
        "v-65cf4b51",
        "v-491b68e8",
        "v-e269e068",
        "v-0ff677f2",
        "v-6c22ecb0",
        "v-7027d348",
        "v-39beb45d",
        "v-5e595f02",
        "v-b5cf85b0"
      ]
    },
    "hexo": {
      "key": "hexo",
      "scope": "tags",
      "path": "/tag/hexo/",
      "pageKeys": [
        "v-8ebd8a44",
        "v-549711b8"
      ]
    },
    "github": {
      "key": "github",
      "scope": "tags",
      "path": "/tag/github/",
      "pageKeys": [
        "v-8ebd8a44"
      ]
    },
    "markdown": {
      "key": "markdown",
      "scope": "tags",
      "path": "/tag/markdown/",
      "pageKeys": [
        "v-71aca858"
      ]
    },
    "小程序": {
      "key": "小程序",
      "scope": "tags",
      "path": "/tag/小程序/",
      "pageKeys": [
        "v-54d9e9c2"
      ]
    },
    "npm": {
      "key": "npm",
      "scope": "tags",
      "path": "/tag/npm/",
      "pageKeys": [
        "v-1222c058"
      ]
    },
    "cookie": {
      "key": "cookie",
      "scope": "tags",
      "path": "/tag/cookie/",
      "pageKeys": [
        "v-63b2ef91"
      ]
    },
    "storage": {
      "key": "storage",
      "scope": "tags",
      "path": "/tag/storage/",
      "pageKeys": [
        "v-63b2ef91"
      ]
    },
    "indexedDB": {
      "key": "indexedDB",
      "scope": "tags",
      "path": "/tag/indexedDB/",
      "pageKeys": [
        "v-63b2ef91"
      ]
    },
    "原型": {
      "key": "原型",
      "scope": "tags",
      "path": "/tag/原型/",
      "pageKeys": [
        "v-32be9db2"
      ]
    },
    "webpack": {
      "key": "webpack",
      "scope": "tags",
      "path": "/tag/webpack/",
      "pageKeys": [
        "v-7f20e659",
        "v-db97e196"
      ]
    },
    "mpvue": {
      "key": "mpvue",
      "scope": "tags",
      "path": "/tag/mpvue/",
      "pageKeys": [
        "v-2e2b0efa"
      ]
    },
    "vant": {
      "key": "vant",
      "scope": "tags",
      "path": "/tag/vant/",
      "pageKeys": [
        "v-2e2b0efa"
      ]
    },
    "css": {
      "key": "css",
      "scope": "tags",
      "path": "/tag/css/",
      "pageKeys": [
        "v-31e4738d",
        "v-4f2b2c50",
        "v-db97e196"
      ]
    },
    "axios": {
      "key": "axios",
      "scope": "tags",
      "path": "/tag/axios/",
      "pageKeys": [
        "v-368015ed"
      ]
    },
    "javascript": {
      "key": "javascript",
      "scope": "tags",
      "path": "/tag/javascript/",
      "pageKeys": [
        "v-05d85f8d",
        "v-318df56c",
        "v-75d48a2e",
        "v-a2dcaef6",
        "v-5734b83e",
        "v-327cbd60",
        "v-014afd87",
        "v-3b6fbcb6",
        "v-72a6a583",
        "v-03b6ac0e",
        "v-2d399ebb",
        "v-986d8176",
        "v-3f17de72",
        "v-0d3a2328",
        "v-513f8d42",
        "v-3b0e0804",
        "v-26574814",
        "v-c37b03ce",
        "v-4bbfad74",
        "v-a0db9738",
        "v-60f647eb"
      ]
    },
    "react": {
      "key": "react",
      "scope": "tags",
      "path": "/tag/react/",
      "pageKeys": [
        "v-052a06a3"
      ]
    },
    "proxy": {
      "key": "proxy",
      "scope": "tags",
      "path": "/tag/proxy/",
      "pageKeys": [
        "v-3b6fbcb6"
      ]
    },
    "红宝书": {
      "key": "红宝书",
      "scope": "tags",
      "path": "/tag/红宝书/",
      "pageKeys": [
        "v-86cd0aa8"
      ]
    },
    "回忆录": {
      "key": "回忆录",
      "scope": "tags",
      "path": "/tag/回忆录/",
      "pageKeys": [
        "v-20358fac",
        "v-7c4e4e8d",
        "v-328cc28c",
        "v-3693d5a4"
      ]
    },
    "charts": {
      "key": "charts",
      "scope": "tags",
      "path": "/tag/charts/",
      "pageKeys": [
        "v-7b8811ec"
      ]
    },
    "旅游": {
      "key": "旅游",
      "scope": "tags",
      "path": "/tag/旅游/",
      "pageKeys": [
        "v-dc7de658"
      ]
    },
    "开发问题": {
      "key": "开发问题",
      "scope": "tags",
      "path": "/tag/开发问题/",
      "pageKeys": [
        "v-b25a9d7c"
      ]
    },
    "游戏, 电影, 书籍": {
      "key": "游戏, 电影, 书籍",
      "scope": "tags",
      "path": "/tag/游戏, 电影, 书籍/",
      "pageKeys": [
        "v-a625822a"
      ]
    },
    "事件时间线": {
      "key": "事件时间线",
      "scope": "tags",
      "path": "/tag/事件时间线/",
      "pageKeys": [
        "v-7f7258e1"
      ]
    }
  },
  "categories": {
    "随笔": {
      "key": "随笔",
      "scope": "categories",
      "path": "/categories/随笔/",
      "pageKeys": [
        "v-a6f5d7d0",
        "v-20358fac",
        "v-7b8811ec",
        "v-7c4e4e8d",
        "v-dc7de658",
        "v-b25a9d7c",
        "v-328cc28c",
        "v-a625822a",
        "v-7f7258e1",
        "v-3693d5a4"
      ]
    },
    "框架": {
      "key": "框架",
      "scope": "categories",
      "path": "/categories/框架/",
      "pageKeys": [
        "v-52bf07b1",
        "v-54d9e9c2",
        "v-6a22b4f2",
        "v-d79d234a",
        "v-08988cde",
        "v-2e2b0efa",
        "v-368015ed",
        "v-65cf4b51",
        "v-052a06a3",
        "v-491b68e8",
        "v-e269e068",
        "v-0ff677f2",
        "v-6c22ecb0",
        "v-7027d348",
        "v-39beb45d",
        "v-5e595f02",
        "v-b5cf85b0"
      ]
    },
    "其它": {
      "key": "其它",
      "scope": "categories",
      "path": "/categories/其它/",
      "pageKeys": [
        "v-8ebd8a44",
        "v-71aca858",
        "v-549711b8"
      ]
    },
    "语言": {
      "key": "语言",
      "scope": "categories",
      "path": "/categories/语言/",
      "pageKeys": [
        "v-1222c058",
        "v-63b2ef91",
        "v-32be9db2",
        "v-31e4738d",
        "v-05d85f8d",
        "v-318df56c",
        "v-75d48a2e",
        "v-a2dcaef6",
        "v-327cbd60",
        "v-4f2b2c50",
        "v-014afd87",
        "v-3b6fbcb6",
        "v-72a6a583",
        "v-03b6ac0e",
        "v-986d8176",
        "v-3f17de72",
        "v-0d3a2328",
        "v-3b0e0804",
        "v-26574814",
        "v-c37b03ce",
        "v-4bbfad74",
        "v-db97e196",
        "v-60f647eb"
      ]
    },
    "打包": {
      "key": "打包",
      "scope": "categories",
      "path": "/categories/打包/",
      "pageKeys": [
        "v-7f20e659"
      ]
    },
    "echarts": {
      "key": "echarts",
      "scope": "categories",
      "path": "/categories/echarts/",
      "pageKeys": [
        "v-5734b83e"
      ]
    },
    "javascript": {
      "key": "javascript",
      "scope": "categories",
      "path": "/categories/javascript/",
      "pageKeys": [
        "v-2d399ebb",
        "v-513f8d42",
        "v-a0db9738"
      ]
    },
    "阅读": {
      "key": "阅读",
      "scope": "categories",
      "path": "/categories/阅读/",
      "pageKeys": [
        "v-86cd0aa8"
      ]
    }
  },
  "timeline": {}
}